### ISSUE TITLE
Lock/Close status does not work

### ISSUE THREAD

**Issue by KarlisVitols** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#10]
Running Redmine version 4.1.1.stable.
Running Project Enumerations plugin version 1.3.13.

Plugin works in general OK, except: If Enumeration is locked or closed, possible value will not be present in the dropdown list (depends on the Custom Field status configuration).

In other words - even if I choose to lock or close specific enumeration value, it still shows up in drop-down list.

**Comment by Utopism** [comment]
Hi @KarlisVitols,
Just updated my Redmine to 4.1.1 and tested this, and found no issue.
Values are correctly displayed depending on the configuration of the CustomField :
![image](https://user-images.githubusercontent.com/540464/79513668-aefa6b80-8044-11ea-91a5-0158912c47fc.png)

**Comment by Utopism** [comment]
Hi @KarlisVitols, can I close this issue, do you agree that the behaviour is coherent ?

**Comment by KarlisVitols** [comment]
@Utopism Thank you, it works! I had missed the part that in Administration > Custom Fields --> selected project enumeration needs to be configured as shown in your screenshot (to be visible under specific enumeration statuses)! We can close this issue.

**Comment by Utopism** [comment]
@KarlisVitols, yes let's close it (updated the readme with the screen capture).
