### ISSUE TITLE
ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0000000008e9beb8>:0x0000000008e67f78> Did you mean?

### ISSUE THREAD

**Issue by linchao0815** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#14]
version: Bitnami\redmine-4.1.1-7
When I setup a "Project List of Values" of custom field.
It will be ERROR !

---------------------------------
production.log
...
Started GET "/redmine/projects/easy_for_cat/settings" for 127.0.0.1 at 2021-01-20 11:21:35 +0800
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"easy_for_cat"}
  Current user: linchao (id=101)
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/settings.html.erb within layouts/base (1285.0ms)
Completed 500 Internal Server Error in 2193ms (ActiveRecord: 31.7ms)
  
ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0000000008e9beb8>:0x0000000008e67f78>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  
plugins/redmine_wiki_extensions/lib/wiki_extensions_projects_helper_patch.rb:22:in `project_settings_tabs'
plugins/redmine_smile_project_enumerations_custom_field_format/lib/helpers/smile_helpers_projects.rb:22:in `project_settings_tabs_with_project_enumerations'
plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/projects_helper_patch.rb:28:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__625753173_74791740'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by Utopism** [comment]
Hi, by any chance, do you use also the **redmine_dmsf** plugin ?
Please have a look here : https://github.com/danmunn/redmine_dmsf/issues/845

**Comment by Utopism** [comment]
@linchao0815 any news ?

**Comment by linchao0815** [comment]
Sorry Now I can not reproduce same case.

**Comment by Utopism** [comment]
@linchao0815 thanks.
