### ISSUE TITLE
Error install in Redmine 4.0.5

### ISSUE THREAD

**Issue by koren85** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#15]
Hi!
I get error in Redmine 4.0.5

How can I solve this errror? Thanks!

logs in production.log

<pre> 
root@46249f4eaaf6:/home/redmine/redmine# cat ./log/production.log
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user : redmine
Starting That Issue Reply Button plugin for Redmine
Starting Westaco Versions Plugin for Redmine
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :visible. Overwriting existing method Principal.visible.
o=>
o=>\__ redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>0                                     plugin  redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>----- CONTROLLERS
o=>1     ProjectsController    instance_methods  settings < (SM::CO::ProjectsOverride::ProjectEnumerations)
o=>----- HELPERS
o=>2     ProjectsHelper        instance_methods  project_settings_tabs_with_project_enumerations < (SM::HO::ProjectsOverride::ProjectEnumerations)
o=>----- MODELS
o=>4     Project               instance_methods  shared_enumerations; shared_list_values < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>5     Project                         scopes  joins_custom_fields < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>/--
Migrating to FixMigrationName (20190901140000)
Migrating to CreateProjectEnumerations (20190904123000)
Migrating to AddProjectEnumerationPosition (20191204234500)
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Starting That Issue Reply Button plugin for Redmine
Starting That Issue Reply Button plugin for Redmine
Starting Westaco Versions Plugin for Redmine
Starting Westaco Versions Plugin for Redmine
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :visible. Overwriting existing method Principal.visible.
Creating scope :visible. Overwriting existing method Principal.visible.
o=>
o=>\__ redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>0                                     plugin  redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>----- CONTROLLERS
o=>1     ProjectsController    instance_methods  settings < (SM::CO::ProjectsOverride::ProjectEnumerations)
o=>----- HELPERS
o=>2     ProjectsHelper        instance_methods  project_settings_tabs_with_project_enumerations < (SM::HO::ProjectsOverride::ProjectEnumerations)
o=>----- MODELS
o=>4     Project               instance_methods  shared_enumerations; shared_list_values < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>5     Project                         scopes  joins_custom_fields < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>/--
o=>
o=>\__ redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>0                                     plugin  redmine_smile_project_enumerations_custom_field_format V1.3.14
o=>----- CONTROLLERS
o=>1     ProjectsController    instance_methods  settings < (SM::CO::ProjectsOverride::ProjectEnumerations)
o=>----- HELPERS
o=>2     ProjectsHelper        instance_methods  project_settings_tabs_with_project_enumerations < (SM::HO::ProjectsOverride::ProjectEnumerations)
o=>----- MODELS
o=>4     Project               instance_methods  shared_enumerations; shared_list_values < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>5     Project                         scopes  joins_custom_fields < (SM::MO::ProjectOverride::ProjectEnumerations)
o=>/--
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
Creating scope :system. Overwriting existing method Enumeration.system.
o=>
o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
o=>Application user :
</pre> 

Installed plugins:
westaco_versions

**Comment by Utopism** [comment]
Hi, what is the error ? that the plugin is loading an infinite times ?
where is installed your plugin in your redmine structure ?
do you use symlinks ?

**Comment by koren85** [comment]
Hi! Yes, I see it in the log and Redmine doesn't work. If this is not a bug, what does it mean? I am using sameersbn \ redmine 4.0.5 docker image. symlinks are used for ./logs

**Comment by Utopism** [comment]
Hi, How did you installed the plugin in your docker instance ?, is it only present once ? in the correct **plugin** directory ?

**Comment by koren85** [comment]
Hi, Yes the plugin is installed properly according to all recommendations. The plugin is singular and located in the `vendor/plugins/redmine_smile_project_enumerations_custom_field_format` folder

**Comment by Utopism** [comment]
Hi, is it possible for you to try to install it directly in the **plugins/** folder ?

**Comment by Utopism** [comment]
Hi, as I have no reply to my question, I am closing this issue. I can reopen it if new information is provided.
