### ISSUE TITLE
Field with format = Project enumeration not loading values when hitting "Create and continue"

### ISSUE THREAD

**Issue by fabilewk** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#16]
Hi,

We installed the plugin redmine_smile_project_enumerations_custom_field_format on Redmine (version 3.4.6.stable) a couple of weeks ago.
After that, we created a new custom field with format = _Project enumeration_ and added it for _Spent time entries_.

We found the following issue when creating time entries:

- if the user clicks the "Create" button, it works ok
- if the user clicks the "Create and continue" button, after creating the first time entry, the dropdown list gets empty and there's no way of continue creating another one, since that field has no values anymore. I mean the values for that custom field are not loaded again after you click "Create and continue".
See https://i.imgur.com/havX4If.png. 

Has anyone experienced that issue before?

We're not developers so we're not sure how to fix that.

Any help would be much appreciated.

Thanks!

**Comment by Utopism** [comment]
Hi, it's a weird issue.
Sorrily, I just tested on a V4.1 Redmine, and the list of values is kept after Create and continue.
Do you have any other plugin that could interfere with this plugin ?
The way that this plugin adds the new custom fields is a pretty Redmine standard way, so I wonder how could it fail to load the values on your instance.
Could you get the logs on the server for what happens after the Create and continue button is clicked ?

**Comment by fabilewk** [comment]
Hi, thanks for your quick reply!

Something I forgot to mention is that this weird behavior happens when saving a time entry **from within a project**. I mean you have to be inside a project (e.g. http://redmine/projects/xxxxxxxxxxx/time_entries/new) to be able to reproduce this issue. When saving a time entry from within an issue, after clicking "Create and continue", the options of the dropdown list are loaded as expected.

Yes, we have some other plugins that we installed a while ago but I'm not sure if some of those could be interfering.

I'll try to get the logs from the production server and will get back to you.

Thanks!

**Comment by Utopism** [comment]
* Okay this is a very specific issue, I suppose it is a bug in the **ProjectEnumerationFormat.possible_values_enumerations** method,
I had a quick look and did not found something obvious.

**Comment by Utopism** [comment]
This is an issue with Redmine,

Proposed a patch here : https://www.redmine.org/issues/35066
You can apply this patch if you want, should be ok with a recent Redmine version.

**Comment by fabilewk** [comment]
Ok, we'll take a look at it.
Thanks!

**Comment by Utopism** [comment]
Closing this issue as a patch that solves it was provided.
