### ISSUE TITLE
support more standard format in normal custom_field

### ISSUE THREAD

**Issue by tainewoo** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#2]
Thank you for such a great plugin.
seems it's using the model of version to adding the new project enumerations.
is it possible to support more formats?
so we can move most of the redmine custom fields to project custom fields, so project management role (or maybe permission can be defined in Role&Permission) can define their value.
Currently the Redmine Custom Fields can only be defined and managed by Administrator, it's not convient enough because some of the fields needs to add new pre-defined value by request.

**Comment by Utopism** [comment]
You're welcome.

The plugin is only using the Version as model for shared and status management. For the rest it's a simple list management.
What are the **other formats you want to see** ?, except **key / value Type** custom field, that I have already thought to implement, I don't see other Custom Field types on which we can add the feature to get **possible values** in the project. Versions Type custom field already get their values in the project.

The aim of this plugin is not to change the philosophy of Redmine by transfering process definition to the projects. Other Project management tools allow this.

**Comment by tainewoo** [comment]
Hi @Utopism ,
Yes, mostly I think the Key/value list is most needed.

I'm thinking the usage of this plugin. We can use it to manage the pre-defined values of custom fields directly in the project by role, without turn to Administrator to update the pre-defined value again and again.
Mostly I use these type of custom fields: 
**Date (input), 
Key/Value List (allowed values can only be managed by Administrator), 
Link (input), 
Long Text (input), 
Text (input),
User (managed), 
Version (managed by project).**
For others, they are either input or can be managed by users/projectmanagement, but for the Key/Value List. And the Key/Value List is just the type we use mostly.

So if the Key/Value List can be implemented to this plugin, it would be very useful.

**Comment by tainewoo** [comment]
Maybe also the Long Text, because differfent project may need different default value.

Actually if there is option of the Administration, do define some of the Redmine Custom Field to have the permission to define the value/DefaultValue by specific role of the project, it would be ok too.

**Comment by Utopism** [comment]
Hi,
The difference between **Key/Value** and **List** FieldFormat is that Key/Value stores the **id** in the **custom_values** tables, and List stores the **value** when it is changed in the customized model.
I have developed the plugin with the Key/Value behavior.
So I am adding soon a new **List Value Field Format** that will work like List Custom Field Format.

**Comment by tainewoo** [comment]
Hi @Utopism ,
Thank you for your great work.
And sorry for my absence last weekend and late response.

Let me describe the behavior/advantage of Version, Key/Value list, and list.

**Version** (seems it's the prototype of current ProjectEnumeration)
Advantage: 
use key/id to store, and use the value to display.
has the status for each record.
has the option "share" for each record, and this is VERY useful for ProjectEnumeration.
Disadvantage:
Method to create/manage values is not convenient, and no method to order the values.
Status: open/locked/closed, but actually open/closed is enough I think, because there is no rule to define different behavior for lock/closed.

**Key/Value list**
Advantage:
use key/id to store, and use the value to display.
Has the "Active" and "Disactive" status for each record.
Easy to create/mamage predefined values, and order is available.
Disadvantage:
Original Key/Value list doesn't has "share" option.

**List:**
use value string to store, no key/id, full string will be stored/used
no activa/disactive status
no share option

So it would be better if:
1. improve the method of current Version kind ProjectEnumeration for create/manage predefined values (make is similiar with Key/Value list)
2. implement Key/Value list format, also with "Share" option.
3. also the List format.

**Comment by tainewoo** [comment]
Here is the value manage page of one of the Key/Value list format custom field

![KeyValueList](https://user-images.githubusercontent.com/13391232/69962166-5f5d4c80-1548-11ea-9d0e-583d6c47338e.png)

**Comment by Utopism** [comment]
Hi, here is a full comparison of the different Types of Custom Field.
https://owncloud.ennder.fr/index.php/s/naMNzgb3xTiX7Ff
* I am developing the **Project List Value** type
* The order feature has to be developed too.

**Comment by Utopism** [comment]
Please feel free to test V1.0.6 that add the new **Project List Values** field format.

**Comment by tainewoo** [comment]
Hi @Utopism 
Thank you for your great work, I will try the new version for the Project List Values field format and provide the feedback. This plugin is wonderful.

BTW, i use this to check the behavior of all the standard format for normal Redmine Custom Field:
Redmine - Administration - Custom Fields

The current Project Enumeration format comparing to Key/Value list format, is more difficult to create/manage predefined values, to create a value we need multiple click and redirect, and there is no method to order the values. While Key/Value list format can create/modify/manage/order the value in a single form/page, it's easier for user to manage the values.
That's why i also look forward to Key/Value list format, or make current ProjectEnumeration easier to manage the values (just like the method of Key/Value list, it's good).

**Comment by Utopism** [comment]
Hi @tainewoo you're welcome.

I'll consider to update Project Enumeration edition in a single page by Custom Field because this is necessary to add the order feature, be I need to figure how to select the Custom Field.

**Comment by Utopism** [comment]
Hi @tainewoo, please test V1.0.7 that adds new Project Enumeration edition like for Key/Value list.
remains sorting that misses a new position column in the table.

**Comment by tainewoo** [comment]
Hi @Utopism ,
Great news, thank you so much, i'm going to update it right now.

**Comment by tainewoo** [comment]
Hi @Utopism ,

tested failed, after i upgrade to master tip, in the ProjectEnumerations tab, all ProjectEnumerations Custom field is gone, while Project Lists of Values still stay the same as before.
Tested with Redmine4.0.2

![ProjectEnumerations](https://user-images.githubusercontent.com/13391232/70241896-d003a380-17aa-11ea-8a6d-af47e4368d3e.png)


> o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
> o=>Application user : gxxxw
> Creating scope :visible. Overwriting existing method Principal.visible.
> o=>
> o=>\__ redmine_smile_project_enumerations_custom_field_format V1.0.7
> o=>1                                     plugin  redmine_smile_project_enumerations_custom_field_format V1.0.7
> o=>----- CONTROLLERS
> o=>2     ProjectsController    instance_methods  settings < (SM::CO::ProjectsOverride::ProjectEnumerations)
> o=>----- HELPERS
> o=>3     ProjectsHelper        instance_methods  project_settings_tabs < (SM::HO::ProjectsOverride::ProjectEnumerations)
> o=>----- MODELS
> o=>5     Project               instance_methods  shared_enumerations; shared_list_values < (SM::MO::ProjectOverride::ProjectEnumerations)
> o=>/--
> Creating scope :sorted. Overwriting existing method User.sorted.
> Creating scope :sorted. Overwriting existing method Group.sorted.
> Creating scope :system. Overwriting existing method Enumeration.system.
> o=>
> o=>Starting Redmine Smile Project Enumerations Custom Field Format plugin for Redmine
> o=>Application user : gxxxw
> Creating scope :visible. Overwriting existing method Principal.visible.
> o=>
> o=>\__ redmine_smile_project_enumerations_custom_field_format V1.0.7
> o=>1                                     plugin  redmine_smile_project_enumerations_custom_field_format V1.0.7
> o=>----- CONTROLLERS
> o=>2     ProjectsController    instance_methods  settings < (SM::CO::ProjectsOverride::ProjectEnumerations)
> o=>----- HELPERS
> o=>3     ProjectsHelper        instance_methods  project_settings_tabs < (SM::HO::ProjectsOverride::ProjectEnumerations)
> o=>----- MODELS
> o=>5     Project               instance_methods  shared_enumerations; shared_list_values < (SM::MO::ProjectOverride::ProjectEnumerations)
> o=>/--
>

**Comment by Utopism** [comment]
Hi,

1) Can you give me the result of the execution of this instruction in a rails console :
`ProjectEnumeration.joins(:custom_field).collect{|pe| "cf: #{pe.custom_field.name} p:#{pe.project.name}, v=#{pe.value}"}`
2) Can you give me a Screen Capture of the Project List of values tab ?
3) Do you have the edit project enumerations permissions on the project ?

**Comment by Utopism** [comment]
Hi,

Positioning of Project Enumerations possible values is now available. Feel free to test it.

**Comment by tainewoo** [comment]
Hi @Utopism 
i’m now outside and can not access my computer, but the ProjectEnumerations work well on version 1.0.6, but can not be listed from the ProjectEnumeration tab on version 1.0.7, and ProjectListValues work on both1.0.6 and 1.0.7.  After i downgrade back to 1.0.6 the ProjectEnumerations back.

i will try to execute the command when i can access it

**Comment by Utopism** [comment]
Hi @tainewoo,

You have to check also that the ProjectEnumeration CustomField is enabled in the project.

**Comment by tainewoo** [comment]
Hi @Utopism 
Yes sure, they are enabled , and also i have the permission to edit them.
this issue only exists on 1.0.7, but not on 1.0.6.

**Comment by Utopism** [comment]
Hi,

I am going to provide (in less than an hour) a new version with a lot of refactorings. Among them, not enabled Custom Fields in project will be listed.

**Comment by Utopism** [comment]
Here we are,

Please test V1.2.0

**Comment by tainewoo** [comment]
Hi @Utopism 
I use the 1.0.6 to run the command, here is the return:
•cf: Processor p:Atest, v=Intel-i3-5x
•cf: TestIssueProjectListCF p:APP-ZRedmine, v=TestProjectListCF1


and actually i have some ProjectEnumeration initialized, but no values is predefined for them yet, but the CustomFileds are enabled for the project.
Even don't have the link to create values for them (New value xxxxx). And the links exist on 1.0.6.

updated:
now i created values for all ProjectEnumerations type of custom fields, and, on 1.0.7, all of the ProjectEnumerations are still not listed, even don't have the link to create values for them.

The result of "ProjectEnumeration.joins(:custom_field).collect{|pe| "cf: #{pe.custom_field.name} p:#{pe.project.name}, v=#{pe.value}"}" is the same to the result on 1.0.6.

One more info, for the ProjectEnumerations Custom Fields "Processor", i created it from Administration, and enabled it for "All project", and enabled them for some trackers, and added some predefined values for them. But till now, there is no issues created.
And for TestIssueProjectListCF, there are issues created already.

I will test 1.2.0 later today.

**Comment by tainewoo** [comment]
Hi @Utopism 
I tried 1.2.0, problems are still there.
The ProjectEnumerations are listed as "Not enabled on project", actually they are enabled for "All projects", and some trackers using it, but there are no issues created for the trackers, don't know if it's the reason.
The ProjectListsofValues, this time, not displayed anymore on 1.2.0, which is still working on 1.0.6/1.0.7.

**Comment by tainewoo** [comment]
Hi @Utopism ,

for: _enabled_on_project, maybe need to consider:

1. Administration - CustomField, and the custom field is enable as "For all projects", rather than enabled for some of the projects and get them checked one by one.
![ForAllProjects](https://user-images.githubusercontent.com/13391232/70442018-69df8f00-1ad0-11ea-8ab4-6fb80d8dd553.png)

2. some of the fileds can set the value as "share with project tree", or maybe even "share with all projects" (this may only for Administrator)

**Comment by Utopism** [comment]
Hi,

I suppose the issue is *For all projects*. Can you disable it in the Custom Field Configuration ? and see if it's better ?

For point 2. I used the model of Version, that is even more extended than the one for the native **Key / Value** Field format, so I think I will stick to it.

**Comment by Utopism** [comment]
Hi again,

Managed the **Is for all project** case. Should fix the issue.

**Comment by tainewoo** [comment]
Hi @Utopism ,

do i need to customize some page before i can use the v1.3.0?
When i tried to use the v1.3.0, and enter the Project Settings page, 404 errors met.

Log:

 ```
 Rendered projects/settings.html.erb within layouts/base (36.3ms)
Missing template, responding with 404: Missing partial projects/settings/_custom_field_checkbox with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :slim, :rsb]}. Searched in:
  * "/home/redmine-4.0.2/plugins/redmine_smile_project_enumerations_custom_field_format/app/views"
  * "/home/redmine-4.0.2/plugins/additionals/app/views"
  * "/home/redmine-4.0.2/app/views"
  * "/var/lib/gems/2.6.0/gems/redmine_extensions-0.2.16/app/views"

```

**Comment by Utopism** [comment]
Sorry just a missing partial. Just fixed it with V1.3.1

**Comment by tainewoo** [comment]
I will retry now.

**Comment by tainewoo** [comment]
v1.3.1 looks good, it works now.
Thank you so much, i will continue the test.

**Comment by Utopism** [comment]
Great, thanks for your tests. I suppose we will be able to close this issue soon.

**Comment by tainewoo** [comment]
Hi @Utopism 
Yes i’m going to close this issue, thank you for your great effort and help!

**Comment by Utopism** [comment]
Thanks,

Feel free to Star this project, and rate the plugin here :
http://www.redmine.org/plugins/redmine_smile_project_enumerations_custom_field_format

**Comment by tainewoo** [comment]
Sure, already~

**Comment by Utopism** [comment]
Thanks a lot !
