### ISSUE TITLE
uninitialized constant SmileTools: fail to install with redmine4.0.2 production/test

### ISSUE THREAD

**Issue by tainewoo** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#4]
rake aborted!
NameError: uninitialized constant SmileTools
/home/gpusw/redmine-4.0.2/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:77:in `block in <top (required)>'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/lib/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/home/gpusw/redmine-4.0.2/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.6.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by tainewoo** [comment]
find the reason, PR https://github.com/Smile-SA/redmine_smile_project_enumerations_custom_field_format/pull/5 can fix this issue.

**Comment by Utopism** [comment]
Tested it fixes the issue, so I close it
