### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mtashackori** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#6]
I've gotten an error in web:

> Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

> 
and in log file:

> Started GET "/projects/arz/settings" for 127.0.0.1 at 2019-11-28 11:36:18 +0330
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"arz"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 146ms (ActiveRecord: 25.8ms)
  
NameError (uninitialized constant ProjectEnumeration
Did you mean?  ProjectEnumerationsController):
  
lib/plugins/redmine_smile_project_enumerations_custom_field_format/lib/controllers/smile_controllers_projects.rb:33:in `settings'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>
How can I fix it?

**Comment by Utopism** [comment]
Hi,
the plugin should be installed in the redmine standard <APP_ROOT>/plugins folder.
Instead the log file indicates the path **lib/plugins/redmine_smile_project_enumerations_custom_field_format**

**Comment by mtashackori** [comment]
> Hi,
> the plugin should be installed in the redmine standard <APP_ROOT>/plugins folder.
> Instead the log file indicates the path **lib/plugins/redmine_smile_project_enumerations_custom_field_format**

Thanks
