### ISSUE TITLE
value manage permission by project

### ISSUE THREAD

**Issue by tainewoo** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#7]
Hi,

Is there any method to achieve this:
for some of the projects, enable the permission to manage the predefined values for ProjectEnumerations and ProjectValuesofList, 
and some other projects, do not allow to manage the values.

This option can be put in Administration or ProjectSettings, just need this option and no matter where it is and it's enough.

**Comment by tainewoo** [comment]
and it's just a consideration for easier control/administration, if it conflict with this plugin's concept please just ignore.

**Comment by Utopism** [comment]
Hi,

If you need to have ProjectEnumerations values with no right for users except than admins to edit the values, you should use a standard key / value custom field. Does it makes sense ?
It seems complicated to mix the behaviour in a single Custom Field.

**Comment by tainewoo** [comment]
I have this kind of usage.
Project1, with sub projects Project1Subproject1, Project1Subproject2, Project1Subproject3....

ProjectEnumeration enabled for Project1 and all of its subprojects.

To avoid creating same/similar values again and again, i would like the management of the projects to:
1. Only create/manage values on Project1, and all values set to "Share with project tree".
2. Never create/manage values on the subprojects of Project1, because there would be multiple values created in different subproject but with same value, and, would be diffcult to manage the values.

If so, i need to set Project1 to be enabled for create/manage values, while its subproject only using the created values from other projects (here is Project1 in this case).

**Comment by tainewoo** [comment]
Hi @Utopism ,

I just tried v1.3.1, and this issue is not making much sense now, because v1.3.1 will display the shared values to other project, so the management role can see the values if shared.

So if there is the option, it would be better and easier for users.
If not, I think the project management role members can make their own effort not to creating duplicated values too, by double confirm manually before doing that.

**Comment by Utopism** [comment]
You can also add a new role that has no permission to edit the Project Enumeration values, and use it on the sub-projects.

So can we close this issue ?

**Comment by tainewoo** [comment]
Hi @Utopism 
Yes without the option i will try other ways to achieve this.
thank you for your help, i’m about to close this issue.
