### ISSUE TITLE
cant migrate DB

### ISSUE THREAD

**Issue by mpauz** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#8]
Looks like can't migrate because table doesn't exist. Can't understand why. tried on 4,0 and 4,1 redmine, both have same error.
  
rake redmine:plugins:migrate NAME=redmine_smile_project_                                                                                                                     enumerations_custom_field_format RAILS_ENV=production
== 20191204234500 AddProjectEnumerationPosition: migrating ====================
-- add_column(:project_enumerations, :position, :integer, {})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

**Mysql2::Error: Table 'redmine.project_enumerations' doesn't exist: ALTER TABLE `                                                                                                                     project_enumerations` ADD `position` int**
/usr/local/rvm/gems/ruby-2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_q                                                                                                                     uery'

**Comment by Utopism** [comment]
Hi,

Can you give the output of **rails db:migrate:status**
and the result of the following sql command on your redmine database :
`select * from schema_migrations where version like '2019%';`

**Comment by Utopism** [comment]
Don't mind, I know why.

There is an issue in the first migration file name (one un-necessany 0).

I'm trying to bring a fix.

**Comment by Utopism** [comment]
Please test with V1.3.2 that fixes the migration name.

**Comment by mpauz** [comment]
Changed init.rb: 4.0.0 --> 4.0 
It helped, thank you!

**Comment by Utopism** [comment]
Great.

You changed **requires_redmine**, why did it helped ?

**Comment by mpauz** [comment]
Yes, it helped, i don't know why, I'm not good at programming :)

**Comment by Utopism** [comment]
Hello,

I don't think it helped, What helped is that I fixed an issue in the migration files.

**Comment by mpauz** [comment]
Yes you are right :)
I just backup whole application, resend plugin, and install, all works great! :)
Thank you.

**Comment by Utopism** [comment]
Thanks for your tests.

Fell free to star this plugin, and rate it here :
http://www.redmine.org/plugins/redmine_smile_project_enumerations_custom_field_format
