### ISSUE TITLE
only need to list ProjectEnumeration and ProjectValueofList tab in enabled projects

### ISSUE THREAD

**Issue by tainewoo** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#9]
as title, maybe it’s better only need to list ProjectEnumeration and ProjectValueofList tab in enabled projects.
if there is no ProjectEnumerations or ProjectValueofList enabled for the project, the tabs doesn’t need to be rendered

**Comment by tainewoo** [comment]
just like it’s a module, if the module is not enabled for a project its tab will not be show.
and sometimes we only need the management of specific projects to know specific feature of the Redmine

**Comment by tainewoo** [comment]
but this is only a suggestion, not a critical issue

**Comment by Utopism** [comment]
I'm not sure, because having these tabs present shows to the project managers that this feature is available, and on which Custom Field they can enable it.
It can be surprising for beginners to search for this feature and do not find the tabs, until they enable the first custom field for this type.
And of course the tabs don't appear if there is no Custom Field of the right type available.

**Comment by tainewoo** [comment]
or maybe u can try to check if there is related trackers enabled in the project. if trackers with ProjectEnumeration enabled in the project, the tab is shown. if trackers with ProjectValueofList enabled in the project, the tab is shown.
normally the Administrator will design how many fields are enabled for each tracker, what managers need to do is to crate/manage the values of them if they enable the trackers. managers will not care the values if they don’t even enable related trackers in their project, that means for the project that kind of trackers are not needed.

**Comment by Utopism** [comment]
Hi @tainewoo that's a good point. I'm pretty busy these days, i'll see if I have time to implement this in the next days.

**Comment by tainewoo** [comment]
Hi @Utopism 

Thank you that you will consider this change.
And this plugin is good enough currently, this is not a critical issue, you can take your time on it.

**Comment by tainewoo** [comment]
Hi @Utopism 
And you also need to consider the values which is set to be shared with other projects, and also Administrator has a special permission to set the value to share with any project, while other management role can only share with project tree as max.

So, the situation would be too complex.

So, maybe you can forget this issue and just let it go, i realized it's kind of complicated situation.

**Comment by tainewoo** [comment]
Hi @Utopism ,

I'm going to close this issue because i think currently the flow is good enough.
